apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMTAuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImJtRnVaR2x6YUhkaGNqcE9ZVzVrZFVBeU1qRXgiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson